name: Deploy Next.js to Vercel

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - staging
      - main
  pull_request:
    branches:
      - dev
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: List files in project directory
        run: |
          echo "Listing files in project directory:"
          ls -la
          echo "Current directory: $(pwd)"

      - name: Check for package-lock.json
        id: check-lock-file
        run: |
          if [ -f "package-lock.json" ]; then
            echo "Lock file found"
            echo "lockfile=true" >> $GITHUB_OUTPUT
          else
            echo "Lock file not found"
            echo "lockfile=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies (with package-lock.json)
        if: steps.check-lock-file.outputs.lockfile == 'true'
        run: npm ci

      - name: Install dependencies (without package-lock.json)
        if: steps.check-lock-file.outputs.lockfile == 'false'
        run: npm install

      - name: Build Next.js project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts for Vercel
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Notify Deployment Success
        run: echo "Deployment to Vercel successful!"