name: Deploy Next.js to Vercel

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - staging
      - main
  pull_request:
    branches:
      - dev
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: List repository contents
        run: |
          echo "Repository root contents:"
          ls -la
          echo "shawazi_magezi directory contents:"
          ls -la shawazi_magezi

      - name: Install dependencies
        working-directory: ./shawazi_magezi
        run: npm ci

      - name: Build Next.js project
        working-directory: ./shawazi_magezi
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        working-directory: ./shawazi_magezi
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts for Vercel
        working-directory: ./shawazi_magezi
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: ./shawazi_magezi
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Notify Deployment Success
        run: echo "Deployment to Vercel successful!"