name: Deploy Next.js to Vercel

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - staging
      - main
  pull_request:
    branches:
      - dev
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./shawazi_magezi/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/shawazi_magezi/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: ./shawazi_magezi
        run: npm install

      - name: Build Next.js project
        working-directory: ./shawazi_magezi
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./shawazi_magezi
        run: npm install

      - name: Deploy to Vercel
        uses: vercel/action@v2
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          working-directory: ./shawazi_magezi

      - name: Notify Deployment Success
        run: echo "Deployment to Vercel successful!"
